### ISSUE TITLE
Strong Name error

### ISSUE THREAD

**Issue by Og1Kenobi** [EldinZenderink/SimpleIRCLib#4]
Now i am getting this error when i try to run it

Severity    Code    Description Project File    Line    Source  Suppression State
Warning     Referenced assembly 'SimpleIRCLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.  frmiWedgeChat   C:\Users\Jonathan\Documents\Visual Studio 2015\Projects\SimpleIRCLib-master\FormExample\CSC     Build

**Comment by EldinZenderink** [comment]
I have not fully read up on signing libraries (so that it can't be pulled apart) and didnt see a point doing so. This should normally not be an issue (as in that the previous versions worked as well, they weren't signed either).. there are a few solutions, the easiest one is deleting the current library and reinstalling it through nuget, or just get it from this github. There are more solutions to this problem which would require a bit more time to setup, which can be found here: http://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error

**Comment by Og1Kenobi** [comment]
it looks like when i embed this i have to not sign my project as well.  looks like an all or nothing scenario without having to go down a rabbit hole.
